### ISSUE TITLE
Playground content editor in unexpected position

### ISSUE THREAD

**Issue by msujew** [langium/langium-website#107]
After merging https://github.com/langium/langium-website/pull/99, changing the grammar results in a re-layouting of the content editor into a very unexpected position:

![image](https://user-images.githubusercontent.com/4377073/204138881-4c77e3ab-454d-407d-bc64-a5b508cae826.png)

**Comment by Lotes** [comment]
Which browser have you used?

**Comment by msujew** [comment]
@Lotes The issue only seems to happen on FireFox, interesting. I can't reproduce it on Chromium.

**Comment by spoenemann** [comment]
I can reproduce this on Safari *if I change the zoom level* (cmd +/-)

**Comment by Lotes** [comment]
For #100 there is not such a problem. Tested on 3 browsers: Chrome, FireFox, Safari.
