### ISSUE TITLE
Some code highlighting is hard to read

### ISSUE THREAD

**Issue by luan-xiaokun** [langium/langium-website#112]
The highlighting of some code in the tutorial is hard to read, check the following screenshot. They look the same on both Chrome and Firefox.

(BTW, the tutorial is really great, I believe it would be helpful for newcomers)

![图片](https://user-images.githubusercontent.com/43921595/206899216-f3ed093d-9f0e-4d68-9837-71a0066d6b20.png)

**Comment by msujew** [comment]
This is getting fixed with https://github.com/langium/langium-website/pull/111.
