### ISSUE TITLE
Error in Example from blog post

### ISSUE THREAD

**Issue by meysholdt** [langium/langium-website#144]
In https://www.typefox.io/blog/langium-playground

When I click on the following link 
<img width="213" alt="image" src="https://user-images.githubusercontent.com/239422/231393702-29fc1ec3-ee8b-4646-a225-393793b27ab1.png">

I end up in a playground that shows the following error:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/239422/231393854-70d1d8cb-28d8-482e-b484-f72f32199cbb.png">

**Comment by montymxb** [comment]
Thanks for catching that 👍 . I can add a PR for this today, we can probably use `Obj` instead in lieue of `Object` being reserved.
