### ISSUE TITLE
Add MiniLogo to the Showacse

### ISSUE THREAD

**Issue by emilkrebs** [langium/langium-website#152]
It would be nice having https://github.com/langium/langium-minilogo/ on the showcase. Maybe using threejs?

**Comment by emilkrebs** [comment]
> Or just [HTML Canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) to minimize dependencies?

This would be possible and would be more effective for 2d graphics. When talking with @montymxb we thought about using some WebGL library to maybe be able to draw 3d graphics in the future.

**Comment by spoenemann** [comment]
Ok feel free to experiment. But I'd like to keep the complexity of the website under control. Remember that all code that is written must be maintained over time.
