### ISSUE TITLE
Playground Bug when Identical terminal rules submitted.

### ISSUE THREAD

**Issue by NigelWSewell** [langium/langium-website#163]
While developing a JavaDoc Extractor to test Langium, It was found that while inserting 2 terminal rules with the same profile caused no error message to appear, and the Content to be 'Loading...' forever. 

The grammar is under development, hence the clear failure in contradictory statements, but should not cause the playground to crash in this way.

### Recording of the Bug
[Screencast from 2023-07-14 19-13-44.webm](https://github.com/langium/langium-website/assets/90779026/69bf821f-d860-4148-8e42-2e2271012ac2)

### Text of Grammar
Note that the terminal rules are identical barring the 'hidden'. 

```
grammar JavaDocExtractor

entry Model:
    (jdocs+=JDoc)*;
terminal JDoc: ('/**' -> '*/');

hidden terminal NotJDoc: ('/**' -> '*/');

```

### Text Content

```
/** foo 1 */
person John
person Jane

/* foo 2*/

Hello John!
Hello Jane!

/** foo 4*/
```

### Browser & OS

Google Chrome Version 114.0.5735.198 (Official Build) (64-bit)
OS Ubuntu 23.04
Linux Kernel 6.2.0-24-generic

**Comment by msujew** [comment]
I believe that happens in general every time a grammar is entered that causes the parser initialization to fail. The user grammar worker seems to crash in that case and doesn't recover.
