### ISSUE TITLE
Langium Error References Missing Page on Cyclic Deps

### ISSUE THREAD

**Issue by montymxb** [langium/langium-website#39]
The [dependency-injection.ts](https://github.com/langium/langium/blob/main/packages/langium/src/dependency-injection.ts#L95) file in langium can throw an error on detecting a cycle with a specific message linking to the following page: https://langium.org/docs/di/cyclic-dependencies. However, this page is not published on the langium website, and appears to be missing from the src entirely? 

We should add this page as part of completing documentation for langium

**Comment by spoenemann** [comment]
This could also be a subsection in the "Configuration via Services" chapter.

**Comment by hpopov** [comment]
The [documentation page](https://langium.org/docs/configuration-services/#resolving-cyclic-dependencies) is implemented by https://github.com/langium/langium-website/pull/149

URL update in the error message is performed by https://github.com/langium/langium/pull/1057

I suggest closing this issue as soon as https://github.com/langium/langium/pull/1057 is merged

**Comment by msujew** [comment]
Thanks @hpopov!
