### ISSUE TITLE
Heart Needs a Little Adjustment

### ISSUE THREAD

**Issue by montymxb** [langium/langium-website#47]
The ❤️ at the bottom of the footer page for the [docs](https://langium.org/docs/) is *slightly* too close to the preceding `and`.

![Screen Shot 2022-05-24 at 12 01 12](https://user-images.githubusercontent.com/5070304/170014342-db4ae039-7413-44ef-ab17-10a2d5b74893.png)

It would be great to give it a single space between the two, probably with a non-breaking space, since Hugo seems to consume the whitespace character that is currently present.

**Comment by Sumitsah0** [comment]
Please assign this task to me.

**Comment by KaptainCS3** [comment]
assign me

**Comment by montymxb** [comment]
Closed by #62 , thanks again!
