### ISSUE TITLE
Landing page Feedback

### ISSUE THREAD

**Issue by kaisalmen** [langium/langium-website#6]
Looking good. I just have two remarks.
Browser used for testing is: Google Chrome Version 95.0.4638.69 (64-Bit Windows)

In this horizontal Features listing I see a scroll-bar (which should not be there, I guess) and I would make them smaller horizontally (text lines filled to the end and therefore box is a little smaller:
![image](https://user-images.githubusercontent.com/21079138/141070773-6c333a3e-1b12-4df3-85be-7e7d0269f185.png)

This is more a matter of taste and it can just be a design decision that can be kept, but I find the text is too much condensed horizontally:
![image](https://user-images.githubusercontent.com/21079138/141071665-1cb84b2b-3e87-42c4-9625-89dddce2ffad.png)

**Comment by KatharinaBrinkhaus** [comment]
unfortunately it looks like the fonts are not displayed correctly in Kai's browser. What could be the reason for this?

**Comment by KatharinaBrinkhaus** [comment]
@kaisalmen are there any effects on the page? For example, do the icons come flying into view from below?

**Comment by kaisalmen** [comment]
Yes that works!

**Comment by kaisalmen** [comment]
Firefox 94.0.1 (64-Bit) on Windows
![image](https://user-images.githubusercontent.com/21079138/141075927-2305b043-77f3-4432-a723-a72b5bd08181.png)

**Comment by jbicker** [comment]
> I would make them smaller horizontally (text lines filled to the end and therefore box is a little smaller
That does not work well because they will never have the lines filled evenly and/or some titles will wrap while others not and so on.

**Comment by jbicker** [comment]
> the fonts are not displayed correctly in Kai's browser

What exactly is different with the fonts?

**Comment by KatharinaBrinkhaus** [comment]
> > the fonts are not displayed correctly in Kai's browser
> 
> What exactly is different with the fonts?

The headings and highlights do not have the "Menlo" font. So of course the sizes are completely different.
