### ISSUE TITLE
Netlify Preview Caches without Updating for Changes

### ISSUE THREAD

**Issue by montymxb** [langium/langium-website#65]
It appears out netlify instance currently has no direct configuration, and is running on the default settings. Most of the time this appears to be problem free, and quite convenient. It also signifies that netlify should cache things like `node_modules`, which is generally desirable. However, updating `package.json` isn't necessarily picked up as a change for `node_modules`, and this can cause the build to fail outright on version changes.

The most recent case is #64, where the netflify preview is completely broken since the monaco api was updated. This can be easily rectified by simply retriggering a build and clearing the cache, but this requires explicit permission to be able to do so.

A possible solution may be adding a netlify.toml to this project, and explicitly indicating how we want our preview & production builds to be constructed. This shifts the responsibility for some of these parts onto us, but should allow us to remove these periodic hiccups with builds.

**Comment by kaisalmen** [comment]
@montymxb it was close because it referenced it in 105. We need to see if there are more caching problems beyond node_modules (what you mentioned in #86). If there are, let's re-open this issue.
