### ISSUE TITLE
Breadcrumb "root" leads to Landing page...

### ISSUE THREAD

**Issue by jbicker** [langium/langium-website#8]
...which makes no sense here. Root of breadcrumb should be the Docs root.

<img width="443" alt="Screenshot 2021-11-25 at 09 43 47" src="https://user-images.githubusercontent.com/28291421/143408808-c5d5e8fd-c7ab-4e59-8788-c143183e169f.png">

**Comment by KatharinaBrinkhaus** [comment]
<img width="497" alt="Bildschirmfoto 2021-12-02 um 09 37 33" src="https://user-images.githubusercontent.com/83573872/144387028-b60ef168-b083-4375-9d22-1325c3e7d154.png">

"Guides" should be called "Documentation"

**Comment by spoenemann** [comment]
Yes, and I'd also change the URL segment `guides` back to `docs`.
