### ISSUE TITLE
Change download link to npm link

### ISSUE THREAD

**Issue by jbicker** [langium/langium-website#9]
Here one should see the npm icon as this link leads to the npm page and not a download.

<img width="155" alt="Screenshot 2021-11-25 at 09 48 38" src="https://user-images.githubusercontent.com/28291421/143409483-cc7b0d06-b785-4fd5-b109-cb6765905613.png">

**Comment by KatharinaBrinkhaus** [comment]
Icon should be the npm N - geekdoc->data->menu->more.yml - icon is at geekdoc.svg
