### ISSUE TITLE
Link from 'Langium in the browser' article in the TypeFox blog leads to a 404 page

### ISSUE THREAD

**Issue by theogiraudet** [langium/langium-website#97]
Hello,

I don't really know if it's the good place to post that but the last link of the article ['Langium in the Web Browser'](https://www.typefox.io/blog/langium-web-browser) (in the 'See for Yourself' part) leads to a 404 page on Github instead of, I think, this page: https://github.com/langium/langium-website/tree/main/hugo/content/showcase.

**Comment by kaisalmen** [comment]
Hi @theogiraudet thanks for reporting. I just checked the blog entry and can not reproduce your problem. The link leads to the proper page. I also used different browser. Did you try clean your cache for the page / perform a hard reload? Please, let us know if the problem persists for you, then others can check as well.

**Comment by theogiraudet** [comment]
I tried with Microsoft Edge and Mozilla Firefox and the issue is the same.
The problematic link is the highlighted one in the following screenshot:
![image](https://user-images.githubusercontent.com/28688370/202659930-861b3ca6-5aef-44b4-8e24-0b978a65b2f3.png)
Leading to https://github.com/langium/langium-website/tree/main/showcase
![image](https://user-images.githubusercontent.com/28688370/202660050-ca1c8670-469c-4b41-933b-0edc79034dc7.png)
I also cleaned the cache of Firefox before.

**Comment by kaisalmen** [comment]
@theogiraudet sorry, I was mislead by the headline and I thought you were referring to the article. Yes, the link is broken. Thanks for reporting. We will fix the website.

**Comment by kaisalmen** [comment]
@theogiraudet FYI it is fixed and deployed.
